### ISSUE TITLE
Getting UnicodeEncodeError on Linux

### ISSUE THREAD

**Issue by edgarzhavoronkov** [OzymandiasTheGreat/klembord#6]
I'm getting this error while using klembord on Linux, see the stacktrace:

```
Traceback (most recent call last):
  File "test.py", line 176, in <module>
    main()
  File "test.py", line 172, in main
    klembord.set_text(markdown)
  File "/home/edgar/anaconda3/lib/python3.6/site-packages/klembord/__init__.py", line 333, in set_text
    SELECTION.set_text(text)
  File "/home/edgar/anaconda3/lib/python3.6/site-packages/klembord/__init__.py", line 128, in set_text
    string = text.encode(ASCII)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-10: ordinal not in range(128)
```
It seems to me that the problem is in lnes 128-129 in __init__.py. Why you don't ignore non-ascii symbols?

**Comment by OzymandiasTheGreat** [comment]
Thanks for catching this! Fixed now.
